# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('cor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lingerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Calcinha',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='amoreserumores_app.Item')),
                ('itemType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Lingerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amoreserumores_app.Lingerie'),
        ),
    ]
