# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoreserumores_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
