# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoreserumores_app', '0003_auto_20170209_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
