# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoreserumores_app', '0004_remove_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Lingerie',
            new_name='nome',
        ),
    ]
